name: s2m2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pysciopt
  - jupyter
  - carveme
  - pandas
  - matplotlib
  - pip
  - pip:
    - fluxbound
    - steadiercom
    - pyvis
